version: 2

project_name: too

builds:
  - id: too
    main: ./cmd/too
    binary: too
    ldflags:
      - -s -w -X github.com/arthur-debert/too/internal/version.Version={{.Version}} -X github.com/arthur-debert/too/internal/version.Commit={{.Commit}} -X github.com/arthur-debert/too/internal/version.Date={{.Date}}
    env:
      - CGO_ENABLED=0
    goos: [linux, windows, darwin]
    goarch: [amd64, arm64]
    ignore:
      - goos: windows
        goarch: arm64

before:
  hooks:
    # Generate completions and man pages before archiving
    - ./scripts/gen-completion
    - ./scripts/gen-manpage

archives:
  - id: too-archive
    ids: [too]
    formats: [tar.gz]
    format_overrides:
      - goos: windows
        formats: [zip]
    name_template: "too_{{ .Version }}_{{ .Os }}_{{ .Arch }}"
    files:
      - src: "README.md"
        info:
          mode: 0644
      - src: "LICENSE"
        info:
          mode: 0644
      - src: "completions/*"
        dst: "completions"
        info:
          mode: 0644
      - src: "man/man1/*"
        dst: "man/man1"
        info:
          mode: 0644

checksum:
  name_template: "checksums.txt"

snapshot:
  version_template: "{{ .Version }}-next"

changelog:
  sort: asc
  filters:
    exclude:
      - "^docs:"
      - "^test:"
      - "^chore:"
      - "Merge pull request"
      - "Merge branch"

brews:
  - ids: [too-archive]
    name: too
    repository:
      owner: arthur-debert
      name: homebrew-tools
      token: "{{ .Env.HOMEBREW_TAP_TOKEN }}"
    directory: Formula
    commit_author:
      name: goreleaserbot
      email: bot@goreleaser.com
    homepage: "https://github.com/arthur-debert/too"
    description: "A simple command-line todo list manager"
    license: "MIT"
    test: |
      system "#{bin}/too --help"
    install: |
      bin.install "too"
      
      # Install shell completions
      bash_completion.install "completions/too.bash" if File.exist?("completions/too.bash")
      zsh_completion.install "completions/_too" if File.exist?("completions/_too")
      fish_completion.install "completions/too.fish" if File.exist?("completions/too.fish")
      
      # Install man page
      man1.install "man/man1/too.1.gz" if File.exist?("man/man1/too.1.gz")

# nFPM packages (deb, rpm, etc.)
# https://goreleaser.com/customization/nfpm/
nfpms:
  - id: too
    builds: [too]
    formats: [deb, rpm, apk]
    package_name: too
    file_name_template: "too_{{ .Version }}_{{ .Os }}_{{ .Arch }}"
    homepage: "https://github.com/arthur-debert/too"
    maintainer: "Arthur Debert <arthur@debert.xyz>"
    description: "A simple command-line todo list manager"
    license: "MIT"
    section: utils
    priority: optional
    contents:
      # Man page
      - src: man/man1/too.1.gz
        dst: /usr/share/man/man1/too.1.gz
        file_info:
          mode: 0644
      # Bash completion
      - src: completions/too.bash
        dst: /usr/share/bash-completion/completions/too
        file_info:
          mode: 0644
      # Zsh completion
      - src: completions/_too
        dst: /usr/share/zsh/site-functions/_too
        file_info:
          mode: 0644
      # Fish completion
      - src: completions/too.fish
        dst: /usr/share/fish/vendor_completions.d/too.fish
        file_info:
          mode: 0644

env:
  - PKG_NAME={{ .Env.PKG_NAME }}