name: E2E Tests

on:
  push:
    branches: [ main, tests/shell-e2e ]
  pull_request:
    branches: [ main ]

jobs:
  e2e:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3

    - name: Set up Go
      uses: actions/setup-go@v4
      with:
        go-version: '1.23'

    - name: Install Bats
      run: |
        sudo apt-get update
        sudo apt-get install -y bats

    - name: Build too binary
      run: |
        go build -v ./...
        ./scripts/build --skip-tests

    - name: Run E2E Tests
      run: |
        cd live-tests/e2e
        ./run-tests.sh

    - name: Upload Test Results
      uses: actions/upload-artifact@v3
      if: always()
      with:
        name: e2e-test-results
        path: live-tests/e2e/results/
        retention-days: 30

    - name: Publish Test Results
      uses: EnricoMi/publish-unit-test-result-action@v2
      if: always()
      with:
        files: live-tests/e2e/results/*.xml
        comment_mode: create new
        job_summary: true