name: Release

on:
  push:
    tags:
      - 'v*.*.*'
  workflow_dispatch:

permissions:
  contents: write

jobs:
  goreleaser:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - uses: actions/setup-go@v5
        with:
          go-version: stable

      - name: Install cross-compilation dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y \
            gcc-aarch64-linux-gnu \
            g++-aarch64-linux-gnu

      - name: Set environment variables
        run: |
          echo "PKG_NAME=too" >> $GITHUB_ENV
          echo "GH_USER=arthur-debert" >> $GITHUB_ENV
          echo "GIT_REPO=arthur-debert/too" >> $GITHUB_ENV

      - name: Generate completions and man pages
        run: |
          export CGO_ENABLED=1
          if [ -f scripts/gen-completion ]; then
            ./scripts/gen-completion
          fi
          if [ -f scripts/gen-manpage ]; then
            ./scripts/gen-manpage
          fi

      - uses: goreleaser/goreleaser-action@v6
        with:
          distribution: goreleaser
          version: '~> v2'
          args: release --clean
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          HOMEBREW_TAP_TOKEN: ${{ secrets.HOMEBREW_TAP_TOKEN }}
          PKG_NAME: too